# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: AutoCompilation

on:
  workflow_dispatch:
  push:
    paths:
      - 'source/**'
      - '.github/workflows/AutoCompilation.yml'
      
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame
          pip install pyinstaller

      - name: Init Files(Code)
        run: |
          mkdir temp1\SourceCode\src
          mkdir temp1\SourceCode\img
          mkdir temp1\SourceCode\font
          mkdir temp1\SourceCode\aud
          xcopy /E /I src\* temp1\SourceCode\src
          xcopy /E /I img\* temp1\SourceCode\img
          xcopy /E /I aud\* temp1\SourceCode\aud
          xcopy /E /I font\* temp1\SourceCode\font
          copy config.json temp1\SourceCode
          copy LICENSE temp1\SourceCode
          copy README.md temp1\SourceCode

      - name: Upload SourceCode
        uses: actions/upload-artifact@v4
        with:
          name: SourceCode
          path: temp1\SourceCode

      - name: Create Executable
        run: |
          cd src
          pyinstaller --name=temp --onefile --windowed --icon '..\img\icon.ico' Card.py Coin.py Const.py Game.py Lawn.py Main.py Menu.py Object.py Plant.py RWconfig.py Source.py Zombie.py
          cd ..

      - name: Init Files(Gemini)
        run: |
          mkdir temp2\PVZ\img
          mkdir temp2\PVZ\font
          mkdir temp2\PVZ\aud
          xcopy /E /I img\* temp2\PVZ\img
          xcopy /E /I aud\* temp2\PVZ\aud
          xcopy /E /I font\* temp2\PVZ\font
          copy config.json temp2\PVZ
          copy src\dist\temp.exe 'temp2\PVZ\Plant Vs Zombie Î±.exe'


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Gemini-Artifacts
          path: temp2